// Mocks generated by Mockito 5.4.6 from annotations
// in piano_fitness/test/shared/test_helpers/mock_repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i6;

import 'package:audioplayers/audioplayers.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:piano_fitness/application/models/notification_settings.dart'
    as _i2;
import 'package:piano_fitness/domain/repositories/audio_service.dart' as _i9;
import 'package:piano_fitness/domain/repositories/midi_repository.dart' as _i5;
import 'package:piano_fitness/domain/repositories/notification_repository.dart'
    as _i7;
import 'package:piano_fitness/domain/repositories/settings_repository.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNotificationSettings_0 extends _i1.SmartFake
    implements _i2.NotificationSettings {
  _FakeNotificationSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAudioPlayer_1 extends _i1.SmartFake implements _i3.AudioPlayer {
  _FakeAudioPlayer_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAudioCache_2 extends _i1.SmartFake implements _i3.AudioCache {
  _FakeAudioCache_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCompleter_3<T> extends _i1.SmartFake implements _i4.Completer<T> {
  _FakeCompleter_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IMidiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMidiRepository extends _i1.Mock implements _i5.IMidiRepository {
  MockIMidiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i6.Uint8List> get midiDataStream =>
      (super.noSuchMethod(
            Invocation.getter(#midiDataStream),
            returnValue: _i4.Stream<_i6.Uint8List>.empty(),
          )
          as _i4.Stream<_i6.Uint8List>);

  @override
  _i4.Future<List<_i5.MidiDevice>> listDevices() =>
      (super.noSuchMethod(
            Invocation.method(#listDevices, []),
            returnValue: _i4.Future<List<_i5.MidiDevice>>.value(
              <_i5.MidiDevice>[],
            ),
          )
          as _i4.Future<List<_i5.MidiDevice>>);

  @override
  _i4.Future<void> connectToDevice(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#connectToDevice, [deviceId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendData(_i6.Uint8List? data) =>
      (super.noSuchMethod(
            Invocation.method(#sendData, [data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendNoteOn(int? note, int? velocity, int? channel) =>
      (super.noSuchMethod(
            Invocation.method(#sendNoteOn, [note, velocity, channel]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendNoteOff(int? note, int? channel) =>
      (super.noSuchMethod(
            Invocation.method(#sendNoteOff, [note, channel]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void registerDataHandler(void Function(_i6.Uint8List)? handler) =>
      super.noSuchMethod(
        Invocation.method(#registerDataHandler, [handler]),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterDataHandler(void Function(_i6.Uint8List)? handler) =>
      super.noSuchMethod(
        Invocation.method(#unregisterDataHandler, [handler]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [INotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockINotificationRepository extends _i1.Mock
    implements _i7.INotificationRepository {
  MockINotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> arePermissionsGranted() =>
      (super.noSuchMethod(
            Invocation.method(#arePermissionsGranted, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> scheduleDailyNotification({
    required int? id,
    required String? title,
    required String? body,
    required DateTime? scheduledTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleDailyNotification, [], {
              #id: id,
              #title: title,
              #body: body,
              #scheduledTime: scheduledTime,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> showInstantNotification({
    required int? id,
    required String? title,
    required String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showInstantNotification, [], {
              #id: id,
              #title: title,
              #body: body,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelNotification(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelNotification, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllNotifications, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.PendingNotification>> getPendingNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingNotifications, []),
            returnValue: _i4.Future<List<_i7.PendingNotification>>.value(
              <_i7.PendingNotification>[],
            ),
          )
          as _i4.Future<List<_i7.PendingNotification>>);
}

/// A class which mocks [ISettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockISettingsRepository extends _i1.Mock
    implements _i8.ISettingsRepository {
  MockISettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NotificationSettings> loadNotificationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#loadNotificationSettings, []),
            returnValue: _i4.Future<_i2.NotificationSettings>.value(
              _FakeNotificationSettings_0(
                this,
                Invocation.method(#loadNotificationSettings, []),
              ),
            ),
          )
          as _i4.Future<_i2.NotificationSettings>);

  @override
  _i4.Future<void> saveNotificationSettings(
    _i2.NotificationSettings? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveNotificationSettings, [settings]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveScheduledNotification({
    required int? id,
    required String? title,
    required String? body,
    required DateTime? scheduledTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveScheduledNotification, [], {
              #id: id,
              #title: title,
              #body: body,
              #scheduledTime: scheduledTime,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.ScheduledNotificationData>> getScheduledNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getScheduledNotifications, []),
            returnValue: _i4.Future<List<_i8.ScheduledNotificationData>>.value(
              <_i8.ScheduledNotificationData>[],
            ),
          )
          as _i4.Future<List<_i8.ScheduledNotificationData>>);

  @override
  _i4.Future<void> removeScheduledNotification(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeScheduledNotification, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [IAudioService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAudioService extends _i1.Mock implements _i9.IAudioService {
  MockIAudioService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AudioPlayer createPlayer() =>
      (super.noSuchMethod(
            Invocation.method(#createPlayer, []),
            returnValue: _FakeAudioPlayer_1(
              this,
              Invocation.method(#createPlayer, []),
            ),
          )
          as _i3.AudioPlayer);
}

/// A class which mocks [AudioPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayer extends _i1.Mock implements _i3.AudioPlayer {
  MockAudioPlayer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AudioCache get audioCache =>
      (super.noSuchMethod(
            Invocation.getter(#audioCache),
            returnValue: _FakeAudioCache_2(
              this,
              Invocation.getter(#audioCache),
            ),
          )
          as _i3.AudioCache);

  @override
  String get playerId =>
      (super.noSuchMethod(
            Invocation.getter(#playerId),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#playerId),
            ),
          )
          as String);

  @override
  double get volume =>
      (super.noSuchMethod(Invocation.getter(#volume), returnValue: 0.0)
          as double);

  @override
  double get balance =>
      (super.noSuchMethod(Invocation.getter(#balance), returnValue: 0.0)
          as double);

  @override
  double get playbackRate =>
      (super.noSuchMethod(Invocation.getter(#playbackRate), returnValue: 0.0)
          as double);

  @override
  _i3.PlayerMode get mode =>
      (super.noSuchMethod(
            Invocation.getter(#mode),
            returnValue: _i3.PlayerMode.mediaPlayer,
          )
          as _i3.PlayerMode);

  @override
  _i3.ReleaseMode get releaseMode =>
      (super.noSuchMethod(
            Invocation.getter(#releaseMode),
            returnValue: _i3.ReleaseMode.release,
          )
          as _i3.ReleaseMode);

  @override
  _i3.PlayerState get desiredState =>
      (super.noSuchMethod(
            Invocation.getter(#desiredState),
            returnValue: _i3.PlayerState.stopped,
          )
          as _i3.PlayerState);

  @override
  _i3.PlayerState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i3.PlayerState.stopped,
          )
          as _i3.PlayerState);

  @override
  _i4.Completer<void> get creatingCompleter =>
      (super.noSuchMethod(
            Invocation.getter(#creatingCompleter),
            returnValue: _FakeCompleter_3<void>(
              this,
              Invocation.getter(#creatingCompleter),
            ),
          )
          as _i4.Completer<void>);

  @override
  _i4.Stream<_i3.AudioEvent> get eventStream =>
      (super.noSuchMethod(
            Invocation.getter(#eventStream),
            returnValue: _i4.Stream<_i3.AudioEvent>.empty(),
          )
          as _i4.Stream<_i3.AudioEvent>);

  @override
  _i4.Stream<_i3.PlayerState> get onPlayerStateChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onPlayerStateChanged),
            returnValue: _i4.Stream<_i3.PlayerState>.empty(),
          )
          as _i4.Stream<_i3.PlayerState>);

  @override
  _i4.Stream<Duration> get onPositionChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onPositionChanged),
            returnValue: _i4.Stream<Duration>.empty(),
          )
          as _i4.Stream<Duration>);

  @override
  _i4.Stream<Duration> get onDurationChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onDurationChanged),
            returnValue: _i4.Stream<Duration>.empty(),
          )
          as _i4.Stream<Duration>);

  @override
  _i4.Stream<void> get onPlayerComplete =>
      (super.noSuchMethod(
            Invocation.getter(#onPlayerComplete),
            returnValue: _i4.Stream<void>.empty(),
          )
          as _i4.Stream<void>);

  @override
  _i4.Stream<void> get onSeekComplete =>
      (super.noSuchMethod(
            Invocation.getter(#onSeekComplete),
            returnValue: _i4.Stream<void>.empty(),
          )
          as _i4.Stream<void>);

  @override
  _i4.Stream<String> get onLog =>
      (super.noSuchMethod(
            Invocation.getter(#onLog),
            returnValue: _i4.Stream<String>.empty(),
          )
          as _i4.Stream<String>);

  @override
  set audioCache(_i3.AudioCache? value) => super.noSuchMethod(
    Invocation.setter(#audioCache, value),
    returnValueForMissingStub: null,
  );

  @override
  set desiredState(_i3.PlayerState? value) => super.noSuchMethod(
    Invocation.setter(#desiredState, value),
    returnValueForMissingStub: null,
  );

  @override
  set state(_i3.PlayerState? state) => super.noSuchMethod(
    Invocation.setter(#state, state),
    returnValueForMissingStub: null,
  );

  @override
  set positionUpdater(_i3.PositionUpdater? positionUpdater) =>
      super.noSuchMethod(
        Invocation.setter(#positionUpdater, positionUpdater),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> play(
    _i3.Source? source, {
    double? volume,
    double? balance,
    _i3.AudioContext? ctx,
    Duration? position,
    _i3.PlayerMode? mode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #play,
              [source],
              {
                #volume: volume,
                #balance: balance,
                #ctx: ctx,
                #position: position,
                #mode: mode,
              },
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setAudioContext(_i3.AudioContext? ctx) =>
      (super.noSuchMethod(
            Invocation.method(#setAudioContext, [ctx]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setPlayerMode(_i3.PlayerMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setPlayerMode, [mode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> release() =>
      (super.noSuchMethod(
            Invocation.method(#release, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> seek(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#seek, [position]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setBalance(double? balance) =>
      (super.noSuchMethod(
            Invocation.method(#setBalance, [balance]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setReleaseMode(_i3.ReleaseMode? releaseMode) =>
      (super.noSuchMethod(
            Invocation.method(#setReleaseMode, [releaseMode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setPlaybackRate(double? playbackRate) =>
      (super.noSuchMethod(
            Invocation.method(#setPlaybackRate, [playbackRate]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setSource(_i3.Source? source) =>
      (super.noSuchMethod(
            Invocation.method(#setSource, [source]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setSourceUrl(String? url, {String? mimeType}) =>
      (super.noSuchMethod(
            Invocation.method(#setSourceUrl, [url], {#mimeType: mimeType}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setSourceDeviceFile(String? path, {String? mimeType}) =>
      (super.noSuchMethod(
            Invocation.method(
              #setSourceDeviceFile,
              [path],
              {#mimeType: mimeType},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setSourceAsset(String? path, {String? mimeType}) =>
      (super.noSuchMethod(
            Invocation.method(#setSourceAsset, [path], {#mimeType: mimeType}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setSourceBytes(_i6.Uint8List? bytes, {String? mimeType}) =>
      (super.noSuchMethod(
            Invocation.method(#setSourceBytes, [bytes], {#mimeType: mimeType}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Duration?> getDuration() =>
      (super.noSuchMethod(
            Invocation.method(#getDuration, []),
            returnValue: _i4.Future<Duration?>.value(),
          )
          as _i4.Future<Duration?>);

  @override
  _i4.Future<Duration?> getCurrentPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, []),
            returnValue: _i4.Future<Duration?>.value(),
          )
          as _i4.Future<Duration?>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
